### ISSUE TITLE
edit-graph GML output broken

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#272]
Likely due to a change in NetworkX,

```
$ thapbi_pict edit-graph -d MOL16S.sqlite -i intermediate/MOL16S/ -s -f gml -o summary/MOL16S.edit-graph.gml
Loaded 1874 unique sequences from 18 FASTA files.
Loaded 14 unique sequences from database
DB had 14 sequences (4 not in FASTA), FASTA had 1874 sequences (1864 not in DB).
DB and FASTA had 10 sequences in common; 1878 combined.
Computed 1762503 Levenshtein edit distances between 1878 sequences.
Will draw 1781 nodes with at least one edge (97 are isolated sequences).
Including high abundance isolated sequences, will draw 1878 nodes.
Traceback (most recent call last):
  File "/mnt/.../apps/conda/bin/thapbi_pict", line 8, in <module>
    sys.exit(main())
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/thapbi_pict/__main__.py", line 1421, in main
    sys.exit(options.func(options))
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/thapbi_pict/__main__.py", line 336, in edit_graph
    debug=args.verbose,
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/thapbi_pict/edit_graph.py", line 547, in main
    write_fn(G, "/dev/stdout" if graph_output == "-" else graph_output)
  File "<decorator-gen-686>", line 2, in write_gml
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/networkx/utils/decorators.py", line 239, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 823, in write_gml
    for line in generate_gml(G, stringizer):
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 758, in generate_gml
    yield from stringize(attr, value, ignored_keys, "    ")
  File "/mnt/.../apps/conda/lib/python3.7/site-packages/networkx/readwrite/gml.py", line 719, in stringize
    raise NetworkXError(f"{value!r} is not a string")
networkx.exception.NetworkXError: 1 is not a string
```

**Comment by peterjc** [comment]
Turns out to be due to https://github.com/networkx/networkx/issues/3343 and poor handling of ``numpy.uint64`` which we can cast to a plain ``int`` to fix this.
