### ISSUE TITLE
CI failing edit-graph test due to node name in networkx/pydot

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#457]
See #456,

```
Traceback (most recent call last):
  File "C:\Python310-x64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310-x64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310-x64\Scripts\thapbi_pict.exe\__main__.py", line 7, in <module>
  File "C:\Python310-x64\lib\site-packages\thapbi_pict\__main__.py", line 1661, in main
    sys.exit(options.func(options))
  File "C:\Python310-x64\lib\site-packages\thapbi_pict\__main__.py", line 337, in edit_graph
    return main(
  File "C:\Python310-x64\lib\site-packages\thapbi_pict\edit_graph.py", line 614, in main
    write_fn(G, sys.stdout.buffer)
  File "C:\Python310-x64\lib\site-packages\thapbi_pict\edit_graph.py", line 89, in write_pdf
    placement = nx.drawing.nx_pydot.graphviz_layout(G, "fdp")
  File "C:\Python310-x64\lib\site-packages\networkx\drawing\nx_pydot.py", line 269, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "C:\Python310-x64\lib\site-packages\networkx\drawing\nx_pydot.py", line 312, in pydot_layout
    P = to_pydot(G)
  File "C:\Python310-x64\lib\site-packages\networkx\drawing\nx_pydot.py", line 220, in to_pydot
    raise ValueError(
ValueError: 29de890989becddc5e0b10ecbbc11b1a is not a valid node name while using pydot. Please refer https://github.com/pydot/pydot/issues/258
```

Was working 18 days ago https://ci.appveyor.com/project/peterjc/thapbi-pict/builds/43611258?fullLog=true - changes in dependencies for https://ci.appveyor.com/project/peterjc/thapbi-pict/builds/43781066?fullLog=true include:

* networkx-2.8.1 -> networkx-2.8.3
* pydot-1.4.2 unchanged
* SQLAlchemy-1.4.36 -> SQLAlchemy-1.4.37
* numpy-1.22.3 -> numpy-1.22.4
* pyparsing-3.0.9 unchanged

Nothing much in https://networkx.org/documentation/stable/release/release_2.8.2.html but https://networkx.org/documentation/stable/release/release_2.8.3.html has this:

* https://github.com/networkx/networkx/pull/5667

That's certainly the source of the new exception, but why...?

**Comment by peterjc** [comment]
Could not immediately reproduce this locally on Linux with Python 3.7, turns out recent networkx requires Python 3.8 onwards.

**Comment by peterjc** [comment]
I can reproduce this, and I think it is a false positive in networkx - previously it was happy with single word node names without explicit quotes. Commented on upstream issue.

**Comment by peterjc** [comment]
Test case: ``thapbi_pict edit-graph -k ITS1 -f pdf -o test.pdf``

networkx 2.8.2 works

```
$ thapbi_pict edit-graph -k ITS1 -f pdf -o test.pdf
Loaded 1296 unique ITS1 sequences from DB.
Computed Levenshtein edit distances.
Will draw 1296 nodes with at least one edge (0 are isolated sequences).
```

networkx 2.8.3 fails due to overly strict error handler

```
$ thapbi_pict edit-graph -k ITS1 -f pdf -o test.pdf
Loaded 1296 unique ITS1 sequences from DB.
Computed Levenshtein edit distances.
Will draw 1296 nodes with at least one edge (0 are isolated sequences).
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/bin/thapbi_pict", line 33, in <module>
    sys.exit(load_entry_point('thapbi-pict', 'console_scripts', 'thapbi_pict')())
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/__main__.py", line 1660, in main
    sys.exit(options.func(options))
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/__main__.py", line 337, in edit_graph
    return main(
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/edit_graph.py", line 620, in main
    write_fn(G, handle)
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/edit_graph.py", line 89, in write_pdf
    placement = nx.drawing.nx_pydot.graphviz_layout(G, "fdp")
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 269, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 312, in pydot_layout
    P = to_pydot(G)
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 220, in to_pydot
    raise ValueError(
ValueError: 00064639be0396195c149a91d27e0410 is not a valid node name while using pydot. Please refer https://github.com/pydot/pydot/issues/258
```

networkx 2.8.4 fails due to float attributes being treated as strings:

```
$ thapbi_pict edit-graph -k ITS1 -f pdf -o test.pdf
Loaded 1296 unique ITS1 sequences from DB.
Computed Levenshtein edit distances.
Will draw 1296 nodes with at least one edge (0 are isolated sequences).
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/bin/thapbi_pict", line 33, in <module>
    sys.exit(load_entry_point('thapbi-pict', 'console_scripts', 'thapbi_pict')())
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/__main__.py", line 1660, in main
    sys.exit(options.func(options))
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/__main__.py", line 337, in edit_graph
    return main(
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/edit_graph.py", line 620, in main
    write_fn(G, handle)
  File "/Users/xxx/repositories/thapbi-pict/thapbi_pict/edit_graph.py", line 89, in write_pdf
    placement = nx.drawing.nx_pydot.graphviz_layout(G, "fdp")
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 357, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 406, in pydot_layout
    P = to_pydot(G)
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 302, in to_pydot
    any(
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 303, in <genexpr>
    (_check_colon_quotes(k) or _check_colon_quotes(v))
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 199, in _check_colon_quotes
    return ":" in s and (s[0] != '"' or s[-1] != '"')
TypeError: argument of type 'float' is not iterable
```

That should be fixed by https://github.com/networkx/networkx/pull/5792 so fingers crossed for networkx 2.8.5

**Comment by peterjc** [comment]
networkx 2.8.5 released 18 July appears to fix this: https://pypi.org/project/networkx/2.8.5/

Being used on AppVeyor from PyPI via pip; not yet used on CircleCI via conda-forge - possibly need to explicitly ask for a newer version of Python there.
