### ISSUE TITLE
Intermitent hmmscan failure

### ISSUE THREAD

**Issue by peterjc** [peterjc/thapbi-pict#56]
Seeing this most often when submitting plate level jobs to the cluster, e.g.

```
Traceback (most recent call last):
  File "/home/xxx/bin/thapbi_pict", line 11, in <module>
  File "/home/xxx/lib/python3.5/site-packages/thapbi_pict/__main__.py", line 309, in main
  File "/home/xxx/lib/python3.5/site-packages/thapbi_pict/__main__.py", line 93, in prepare_reads
  File "/home/xxx/lib/python3.5/site-packages/thapbi_pict/prepare.py", line 341, in main
  File "/home/xxx/lib/python3.5/site-packages/thapbi_pict/prepare.py", line 200, in make_nr_its1
  File "/home/xxx/lib/python3.5/site-packages/thapbi_pict/hmm/__init__.py", line 90, in filter_for_ITS1
  File "/home/xxx/lib/python3.5/site-packages/thapbi_pict/hmm/__init__.py", line 63, in run_and_parse_hmmscan
  File "/home/pc40583/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['hmmscan', '--noali', '-T', '6', '--domT', '6', '-o', '/tmp/89522.1.md.q/tmpaf8pvho3/hmmscan.txt', '/home/xxx/lib/python3.5/site-packages/thapbi_pict/hmm/phytophthora_its1.hmm', '/tmp/89522.1.md.q/tmpt9aqc662/dedup_long.fasta']' returned non-zero exit status 1
```

Currently nothing else is captured and reported, and the problem goes away on re-running.

Add a re-try loop?

**Comment by peterjc** [comment]
Actually there does seem to be a little more logging,

```
Error: Unexpected error 6 in opening hmm file /home/xxx/lib/python3.5/site-packages/thapbi_pict/hmm/phytophthora_its1.hmm.
```

I suspect the SGE ``-j yes`` to combine stdout and stderr logging isn't entirely working, because this error was much higher up the file than the traceback.

This could be due to Python buffering output to stdout/stderr?

**Comment by peterjc** [comment]
Hopefully 3b183a1f76d9bbd8f81e2d2f825d39f80f71ce5d will help with the logging

**Comment by peterjc** [comment]
Flushing is helping to get the error and traceback coordinated. Note I have updated to Python 3.7 installed under conda:

```
Error: Unexpected error 6 in opening hmm file /mnt/xxx/apps/conda/lib/python3.7/site-packages/thapbi_pict/hmm/phytophthora_its1.hmm.
...
subprocess.CalledProcessError: Command '['hmmscan', '--noali', '-T', '6', '--domT', '6', '-o', '/tmp/89766.1.md.q/tmpkxf017ef/hmmscan.txt', '/mnt/xxx/apps/conda/lib/python3.7/site-packages/thapbi_pict/hmm/phytophthora_its1.hmm', '/tmp/89766.1.md.q/tmp5ojyags5/dedup_long.fasta']' returned non-zero exit status 1.
```

Also, a new variant,

```
Error: bad file format in HMM file /mnt/xxx/apps/conda/lib/python3.7/site-packages/thapbi_pict/hmm/phytophthora_its1.hmm
...
subprocess.CalledProcessError: Command '['hmmscan', '--noali', '-T', '6', '--domT', '6', '-o', '/tmp/89765.1.md.q/tmpt7l7c2kj/hmmscan.txt', '/mnt/xxx/apps/conda/lib/python3.7/site-packages/thapbi_pict/hmm/phytophthora_its1.hmm', '/tmp/89765.1.md.q/tmp15ymq0xl/dedup_long.fasta']' returned non-zero exit status 1.
```

Again, seems to be ``hmmscan`` having issues accessing the HMM bundled with ``thapbi_pict`` under the Python ``site-packages`` - likely a network issue.

**Comment by peterjc** [comment]
Thus far have only needed 4 attempts when this has failed on our cluster. So the current setting of 5 retries seems to be enough.

(Still don't know what was happening on the network or storage to trigger this - hasn't happened at all the last few days)

**Comment by peterjc** [comment]
Today I was re-running all our plate to date at the same time, and each plate job eventually failed during ``hmmscan`` (even with the higher retry limit with sleeps in between). This does look to be network contention of some sort for the HMM file on a shared drive.

As of 09bb8727c5a814549c2cb1cf2028135a63b6d89d we now cache the HMM files to the local temporary folder, which should be on the compute node's own hard drive. This ought to solve this properly.

If so, we can return the retry limit to a more sensible number of attempts (e.g. 3).
